{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import dash\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "from dash.dependencies import Input, Output, State\n",
    "import pandas_datareader.data as web # requires v0.6.0 or later\n",
    "from datetime import datetime\n",
    "import pandas as pd\n",
    "import os\n",
    "os.environ[\"IEX_API_KEY\"] = \"pk_1822f9fb08ba4b2285e7c1350b377e4a\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "app = dash.Dash()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "nsdq = pd.read_csv('data/NASDAQcompanylist.csv')\n",
    "nsdq.set_index('Symbol', inplace=True)\n",
    "options = []\n",
    "for tic in nsdq.index:\n",
    "    options.append({'label':'{} {}'.format(tic,nsdq.loc[tic]['Name']), 'value':tic})\n",
    "\n",
    "app.layout = html.Div([\n",
    "    html.H1('Stock Ticker Dashboard'),\n",
    "    html.Div([\n",
    "        html.H3('Select stock symbols:', style={'paddingRight':'30px'}),\n",
    "        dcc.Dropdown(\n",
    "            id='my_ticker_symbol',\n",
    "            options=options,\n",
    "            value=['TSLA'],\n",
    "            multi=True\n",
    "        )\n",
    "    ], style={'display':'inline-block', 'verticalAlign':'top', 'width':'30%'}),\n",
    "    html.Div([\n",
    "        html.H3('Select start and end dates:'),\n",
    "        dcc.DatePickerRange(\n",
    "            id='my_date_picker',\n",
    "            min_date_allowed=datetime(2015, 1, 1),\n",
    "            max_date_allowed=datetime.today(),\n",
    "            start_date=datetime(2018, 1, 1),\n",
    "            end_date=datetime.today()\n",
    "        )\n",
    "    ], style={'display':'inline-block'}),\n",
    "    html.Div([\n",
    "        html.Button(\n",
    "            id='submit-button',\n",
    "            n_clicks=0,\n",
    "            children='Submit',\n",
    "            style={'fontSize':24, 'marginLeft':'30px'}\n",
    "        ),\n",
    "    ], style={'display':'inline-block'}),\n",
    "    dcc.Graph(\n",
    "        id='my_graph',\n",
    "        figure={\n",
    "            'data': [\n",
    "                {'x': [1,2], 'y': [3,1]}\n",
    "            ]\n",
    "        }\n",
    "    )\n",
    "])\n",
    "@app.callback(\n",
    "    Output('my_graph', 'figure'),\n",
    "    [Input('submit-button', 'n_clicks')],\n",
    "    [State('my_ticker_symbol', 'value'),\n",
    "    State('my_date_picker', 'start_date'),\n",
    "    State('my_date_picker', 'end_date')])\n",
    "def update_graph(n_clicks, stock_ticker, start_date, end_date):\n",
    "    start = datetime.strptime(start_date[:10], '%Y-%m-%d')\n",
    "    end = datetime.strptime(end_date[:10], '%Y-%m-%d')\n",
    "    traces = []\n",
    "    for tic in stock_ticker:\n",
    "        df = web.DataReader(tic,'iex',start,end,api_key=os.getenv('IEX_API_KEY'))\n",
    "        traces.append({'x':df.index, 'y': df.close, 'name':tic})\n",
    "    fig = {\n",
    "        'data': traces,\n",
    "        'layout': {'title':', '.join(stock_ticker)+' Closing Prices'}\n",
    "    }\n",
    "    return fig"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [29/Sep/2020 15:19:25] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [29/Sep/2020 15:19:25] \"\u001b[37mGET /_dash-dependencies HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [29/Sep/2020 15:19:25] \"\u001b[37mGET /_dash-layout HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [29/Sep/2020 15:19:25] \"\u001b[37mGET /_dash-component-suites/dash_core_components/async-datepicker.v1_12_0m1599150662.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [29/Sep/2020 15:19:27] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [29/Sep/2020 15:19:35] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 1059, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 994, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-3-fdc39ad72e5c>\", line 56, in update_graph\n",
      "    df = web.DataReader(tic,'iex',start,end,api_key=os.getenv('IEX_API_KEY'))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 199, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\data.py\", line 388, in DataReader\n",
      "    return IEXDailyReader(\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\iex\\daily.py\", line 143, in read\n",
      "    return self._read_one_data(self.url, self._get_params(self.symbols))\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 107, in _read_one_data\n",
      "    out = self._read_url_as_StringIO(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 118, in _read_url_as_StringIO\n",
      "    response = self._get_response(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 181, in _get_response\n",
      "    raise RemoteDataError(msg)\n",
      "pandas_datareader._utils.RemoteDataError: Unable to read URL: https://cloud.iexapis.com/stable/stock/market/batch?symbols=TSLA&types=chart&range=5y&token=pk_1822f9fb08ba4b2285e7c1350b377e4a\n",
      "Response Text:\n",
      "b'You have exceeded your allotted message quota. Please enable pay-as-you-go to regain access'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [29/Sep/2020 15:19:48] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 1059, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 994, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-3-fdc39ad72e5c>\", line 56, in update_graph\n",
      "    df = web.DataReader(tic,'iex',start,end,api_key=os.getenv('IEX_API_KEY'))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 199, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\data.py\", line 388, in DataReader\n",
      "    return IEXDailyReader(\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\iex\\daily.py\", line 143, in read\n",
      "    return self._read_one_data(self.url, self._get_params(self.symbols))\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 107, in _read_one_data\n",
      "    out = self._read_url_as_StringIO(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 118, in _read_url_as_StringIO\n",
      "    response = self._get_response(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 181, in _get_response\n",
      "    raise RemoteDataError(msg)\n",
      "pandas_datareader._utils.RemoteDataError: Unable to read URL: https://cloud.iexapis.com/stable/stock/market/batch?symbols=TSLA&types=chart&range=5y&token=pk_1822f9fb08ba4b2285e7c1350b377e4a\n",
      "Response Text:\n",
      "b'You have exceeded your allotted message quota. Please enable pay-as-you-go to regain access'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [29/Sep/2020 15:20:01] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 1059, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 994, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-3-fdc39ad72e5c>\", line 56, in update_graph\n",
      "    df = web.DataReader(tic,'iex',start,end,api_key=os.getenv('IEX_API_KEY'))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 199, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\data.py\", line 388, in DataReader\n",
      "    return IEXDailyReader(\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\iex\\daily.py\", line 143, in read\n",
      "    return self._read_one_data(self.url, self._get_params(self.symbols))\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 107, in _read_one_data\n",
      "    out = self._read_url_as_StringIO(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 118, in _read_url_as_StringIO\n",
      "    response = self._get_response(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 181, in _get_response\n",
      "    raise RemoteDataError(msg)\n",
      "pandas_datareader._utils.RemoteDataError: Unable to read URL: https://cloud.iexapis.com/stable/stock/market/batch?symbols=TSLA&types=chart&range=5y&token=pk_1822f9fb08ba4b2285e7c1350b377e4a\n",
      "Response Text:\n",
      "b'You have exceeded your allotted message quota. Please enable pay-as-you-go to regain access'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [29/Sep/2020 15:20:13] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 1059, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 994, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-3-fdc39ad72e5c>\", line 56, in update_graph\n",
      "    df = web.DataReader(tic,'iex',start,end,api_key=os.getenv('IEX_API_KEY'))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 199, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\data.py\", line 388, in DataReader\n",
      "    return IEXDailyReader(\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\iex\\daily.py\", line 143, in read\n",
      "    return self._read_one_data(self.url, self._get_params(self.symbols))\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 107, in _read_one_data\n",
      "    out = self._read_url_as_StringIO(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 118, in _read_url_as_StringIO\n",
      "    response = self._get_response(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 181, in _get_response\n",
      "    raise RemoteDataError(msg)\n",
      "pandas_datareader._utils.RemoteDataError: Unable to read URL: https://cloud.iexapis.com/stable/stock/market/batch?symbols=TSLA&types=chart&range=5y&token=pk_1822f9fb08ba4b2285e7c1350b377e4a\n",
      "Response Text:\n",
      "b'You have exceeded your allotted message quota. Please enable pay-as-you-go to regain access'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [29/Sep/2020 15:20:29] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 1059, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 994, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-3-fdc39ad72e5c>\", line 56, in update_graph\n",
      "    df = web.DataReader(tic,'iex',start,end,api_key=os.getenv('IEX_API_KEY'))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 199, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\data.py\", line 388, in DataReader\n",
      "    return IEXDailyReader(\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\iex\\daily.py\", line 143, in read\n",
      "    return self._read_one_data(self.url, self._get_params(self.symbols))\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 107, in _read_one_data\n",
      "    out = self._read_url_as_StringIO(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 118, in _read_url_as_StringIO\n",
      "    response = self._get_response(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 181, in _get_response\n",
      "    raise RemoteDataError(msg)\n",
      "pandas_datareader._utils.RemoteDataError: Unable to read URL: https://cloud.iexapis.com/stable/stock/market/batch?symbols=TSLA&types=chart&range=5y&token=pk_1822f9fb08ba4b2285e7c1350b377e4a\n",
      "Response Text:\n",
      "b'You have exceeded your allotted message quota. Please enable pay-as-you-go to regain access'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [29/Sep/2020 15:20:33] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 1059, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 994, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-3-fdc39ad72e5c>\", line 56, in update_graph\n",
      "    df = web.DataReader(tic,'iex',start,end,api_key=os.getenv('IEX_API_KEY'))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 199, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\data.py\", line 388, in DataReader\n",
      "    return IEXDailyReader(\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\iex\\daily.py\", line 143, in read\n",
      "    return self._read_one_data(self.url, self._get_params(self.symbols))\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 107, in _read_one_data\n",
      "    out = self._read_url_as_StringIO(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 118, in _read_url_as_StringIO\n",
      "    response = self._get_response(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 181, in _get_response\n",
      "    raise RemoteDataError(msg)\n",
      "pandas_datareader._utils.RemoteDataError: Unable to read URL: https://cloud.iexapis.com/stable/stock/market/batch?symbols=BOKF&types=chart&range=5y&token=pk_1822f9fb08ba4b2285e7c1350b377e4a\n",
      "Response Text:\n",
      "b'You have exceeded your allotted message quota. Please enable pay-as-you-go to regain access'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [29/Sep/2020 15:20:37] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 1059, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 994, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-3-fdc39ad72e5c>\", line 56, in update_graph\n",
      "    df = web.DataReader(tic,'iex',start,end,api_key=os.getenv('IEX_API_KEY'))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 199, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\data.py\", line 388, in DataReader\n",
      "    return IEXDailyReader(\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\iex\\daily.py\", line 143, in read\n",
      "    return self._read_one_data(self.url, self._get_params(self.symbols))\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 107, in _read_one_data\n",
      "    out = self._read_url_as_StringIO(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 118, in _read_url_as_StringIO\n",
      "    response = self._get_response(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 181, in _get_response\n",
      "    raise RemoteDataError(msg)\n",
      "pandas_datareader._utils.RemoteDataError: Unable to read URL: https://cloud.iexapis.com/stable/stock/market/batch?symbols=BOKF&types=chart&range=5y&token=pk_1822f9fb08ba4b2285e7c1350b377e4a\n",
      "Response Text:\n",
      "b'You have exceeded your allotted message quota. Please enable pay-as-you-go to regain access'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [29/Sep/2020 15:20:47] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 1059, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 994, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-3-fdc39ad72e5c>\", line 56, in update_graph\n",
      "    df = web.DataReader(tic,'iex',start,end,api_key=os.getenv('IEX_API_KEY'))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 199, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\data.py\", line 388, in DataReader\n",
      "    return IEXDailyReader(\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\iex\\daily.py\", line 143, in read\n",
      "    return self._read_one_data(self.url, self._get_params(self.symbols))\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 107, in _read_one_data\n",
      "    out = self._read_url_as_StringIO(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 118, in _read_url_as_StringIO\n",
      "    response = self._get_response(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 181, in _get_response\n",
      "    raise RemoteDataError(msg)\n",
      "pandas_datareader._utils.RemoteDataError: Unable to read URL: https://cloud.iexapis.com/stable/stock/market/batch?symbols=ADBE&types=chart&range=5y&token=pk_1822f9fb08ba4b2285e7c1350b377e4a\n",
      "Response Text:\n",
      "b'You have exceeded your allotted message quota. Please enable pay-as-you-go to regain access'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [29/Sep/2020 15:21:00] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 1059, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\dash\\dash.py\", line 994, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-3-fdc39ad72e5c>\", line 56, in update_graph\n",
      "    df = web.DataReader(tic,'iex',start,end,api_key=os.getenv('IEX_API_KEY'))\n",
      "  File \"C:\\Users\\baoqu\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 199, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\data.py\", line 388, in DataReader\n",
      "    return IEXDailyReader(\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\iex\\daily.py\", line 143, in read\n",
      "    return self._read_one_data(self.url, self._get_params(self.symbols))\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 107, in _read_one_data\n",
      "    out = self._read_url_as_StringIO(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 118, in _read_url_as_StringIO\n",
      "    response = self._get_response(url, params=params)\n",
      "  File \"C:\\Users\\baoqu\\anaconda3\\lib\\site-packages\\pandas_datareader\\base.py\", line 181, in _get_response\n",
      "    raise RemoteDataError(msg)\n",
      "pandas_datareader._utils.RemoteDataError: Unable to read URL: https://cloud.iexapis.com/stable/stock/market/batch?symbols=ADBE&types=chart&range=5y&token=pk_1822f9fb08ba4b2285e7c1350b377e4a\n",
      "Response Text:\n",
      "b'You have exceeded your allotted message quota. Please enable pay-as-you-go to regain access'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [29/Sep/2020 15:21:10] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "if __name__ == '__main__':\n",
    "    app.run_server()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
